title: Coffee, wires and pi
description: Random interests and Obsessions of zatic11
author: zatic11
theme: minima

collections:
  coffee:
    output: true
    permalink: /coffee/:path/
  projects:
    output: true
    permalink: /projects/:path/
  3d-prints:
    output: true
    permalink: /3d-prints/:path/
